name: "Bug report"
description: "Report a problem and include required details"
title: "[Bug]: <short summary>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please complete all required fields.

        • Tell us whether you use the ESPHome integration or the MQTT integration.
        • Attach DEBUG-level logs. See docs/LOGGING_SYSTEM.md for guidance.

  - type: dropdown
    id: integration
    attributes:
      label: Integration type
      description: Which integration are you using with this project?
      options:
        - ESPHome
        - MQTT
        - Both (ESPHome + MQTT)
        - Other / Unsure
    validations:
      required: true

  - type: input
    id: firmware_version
    attributes:
      label: Firmware version (EVERBLU_FW_VERSION)
      description: Found in src/core/version.h or shown at startup in logs.
    validations:
      required: true

  - type: dropdown
    id: chip_family
    attributes:
      label: Chip family
      description: Select the microcontroller family.
      options:
        - ESP8266
        - ESP32
        - Other
    validations:
      required: true

  - type: input
    id: chip_family_other
    attributes:
      label: If "Other", enter chip family
      placeholder: e.g. RP2040
      description: Only fill this if you selected "Other" above.
    validations:
      required: false

  - type: dropdown
    id: board_model
    attributes:
      label: Board / Model
      description: Select your board from the supported PlatformIO environments or choose "Other".
      options:
        - Adafruit HUZZAH ESP8266 (huzzah)
        - WeMos D1 Mini Pro (d1_mini_pro)
        - WeMos D1 Mini (d1_mini)
        - NodeMCU v2 (ESP-12E) (nodemcuv2)
        - ESP32 DevKit (esp32dev)
        - Other (not listed)
    validations:
      required: true

  - type: input
    id: board_model_other
    attributes:
      label: If "Other", enter model name
      placeholder: e.g., TTGO T-Display, custom board
      description: Only fill this if you selected "Other" above.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched the existing issues for duplicates
          required: true
        - label: I am using the latest release or recent commit
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened, and what did you expect to happen?
      placeholder: Clear and concise description of the issue.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps and any minimal configuration to reproduce the issue.
      placeholder: |
        1. ...
        2. ...
        3. ...
      render: text
    validations:
      required: false

  - type: textarea
    id: versions
    attributes:
      label: Versions / environment
      description: ESPHome version, firmware commit/branch, PlatformIO version, Home Assistant version (if applicable), OS, etc.
      render: text
    validations:
      required: false

  - type: textarea
    id: hardware
    attributes:
      label: Hardware details
      description: Board model (ESP8266 variant), CC1101 module details, wiring, power, antenna, distance from meter, etc.
      render: text
    validations:
      required: false

  - type: textarea
    id: diagnostic_questions
    attributes:
      label: Diagnostic questions (helps us narrow down the issue)
      description: Please answer these questions to help diagnose the problem.
      value: |-
        - How far is the CC1101 radio from the water/gas meter? (distance in meters)
        - Have you tried **moving the radio closer to the meter** (e.g., within 2-3 meters) to test if distance/signal is the issue?
        - Are there any **walls, metal obstacles, or other RF sources** between the radio and meter?
        - What type of antenna does your CC1101 module have (wire, PCB trace, external)?
      render: text
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Minimal configuration
      description: Provide a minimal YAML/CPP config that reproduces the problem (redact secrets).
      placeholder: |
        ```yaml
        # Your ESPHome/config YAML here
        ```
      render: yaml
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Debug logs (REQUIRED)
      description: |
        Please paste DEBUG-level logs that capture the issue. Redact any sensitive information.
        See docs/LOGGING_SYSTEM.md for how to enable and collect detailed logs.
      placeholder: |
        ```
        <paste logs here>
        ```
      render: shell
    validations:
      required: false
